const mongoose = require("mongoose");
const Product = require("../models/Product");
const Category = require("../models/Category");

async function seedAccessories() {
  const accessoriesCategory = await Category.findOne({ $or: [{ slug: 'accessories' }, { name: 'Accessories' }] });

  if (!accessoriesCategory) {
    throw new Error("Accessories category not found — ensure categories are seeded (Wigs, Hair Extensions, Accessories)");
  }

  const accessories = [
    {
      name: "Luxury Wig Stand (Adjustable)",
      description: "Premium adjustable wig stand for drying, styling, and storage.",
      price: 8500,
      category: accessoriesCategory._id,
      stock: 50,
      tags: ["wig stand", "storage", "professional"],
    },
    {
      name: "Canvas Wig Block Head",
      description: "Professional canvas wig head for pinning and styling wigs.",
      price: 12000,
      category: accessoriesCategory._id,
      stock: 40,
      tags: ["wig head", "styling", "canvas"],
    },
    {
      name: "Hot Comb (Electric)",
      description: "High-heat electric hot comb for smooth roots and lace.",
      price: 15000,
      category: accessoriesCategory._id,
      stock: 30,
      tags: ["hot comb", "heat styling"],
    },
    {
      name: "Ceramic Flat Iron",
      description: "Ceramic flat iron for sleek, shiny, heat-safe styling.",
      price: 22000,
      category: accessoriesCategory._id,
      stock: 25,
      tags: ["flat iron", "heat tools"],
    },
    {
      name: "Curling Wand",
      description: "Professional curling wand for soft curls and waves.",
      price: 20000,
      category: accessoriesCategory._id,
      stock: 28,
      tags: ["curling wand", "styling"],
    },
    {
      name: "Wide Tooth Detangling Comb",
      description: "Gentle wide-tooth comb for detangling wigs and extensions.",
      price: 2500,
      category: accessoriesCategory._id,
      stock: 120,
      tags: ["comb", "detangling"],
    },
    {
      name: "Silk Wig Storage Bag",
      description: "Silk-lined bag to protect wigs from friction and dust.",
      price: 6000,
      category: accessoriesCategory._id,
      stock: 70,
      tags: ["storage", "silk"],
    },
    {
      name: "Wig Cap (Nude)",
      description: "Breathable nude wig cap for seamless installs.",
      price: 1800,
      category: accessoriesCategory._id,
      stock: 200,
      tags: ["wig cap", "install"],
    },
    {
      name: "Wig Cap (Black)",
      description: "Stretchable black wig cap for secure wear.",
      price: 1800,
      category: accessoriesCategory._id,
      stock: 200,
      tags: ["wig cap", "install"],
    },
    {
      name: "Lace Tint Spray",
      description: "Adjustable lace tint spray for natural scalp blending.",
      price: 7500,
      category: accessoriesCategory._id,
      stock: 60,
      tags: ["lace", "tint", "install"],
    },
    {
      name: "Wig Adhesive Glue",
      description: "Strong-hold lace adhesive for long-lasting installs.",
      price: 9500,
      category: accessoriesCategory._id,
      stock: 55,
      tags: ["wig glue", "install"],
    },
    {
      name: "Wig Adhesive Remover",
      description: "Gentle adhesive remover for lace safety.",
      price: 7000,
      category: accessoriesCategory._id,
      stock: 45,
      tags: ["adhesive remover"],
    },
    {
      name: "Edge Control Brush",
      description: "Dual-ended edge brush for baby hair perfection.",
      price: 2000,
      category: accessoriesCategory._id,
      stock: 150,
      tags: ["edges", "brush"],
    },
    {
      name: "Wig Clips (Set of 4)",
      description: "Secure wig clips for added stability.",
      price: 3000,
      category: accessoriesCategory._id,
      stock: 90,
      tags: ["wig clips", "security"],
    },
    {
      name: "Heat Protectant Spray",
      description: "Protects hair from heat damage during styling.",
      price: 6500,
      category: accessoriesCategory._id,
      stock: 75,
      tags: ["heat protectant"],
    },
    {
      name: "Wig Shampoo (Sulfate-Free)",
      description: "Gentle shampoo for wigs and extensions.",
      price: 8500,
      category: accessoriesCategory._id,
      stock: 65,
      tags: ["wig care", "shampoo"],
    },
    {
      name: "Wig Conditioner",
      description: "Restores softness and shine to wigs.",
      price: 8500,
      category: accessoriesCategory._id,
      stock: 60,
      tags: ["wig care", "conditioner"],
    },
    {
      name: "Hair Mousse",
      description: "Lightweight mousse for curls and sleek looks.",
      price: 5000,
      category: accessoriesCategory._id,
      stock: 85,
      tags: ["styling", "mousse"],
    },
    {
      name: "Foam Wrap Lotion",
      description: "Perfect for wrapping, setting, and molding styles.",
      price: 5500,
      category: accessoriesCategory._id,
      stock: 80,
      tags: ["wrap", "styling"],
    },
    {
      name: "Hair Straightening Brush",
      description: "Electric straightening brush for quick sleek styles.",
      price: 18000,
      category: accessoriesCategory._id,
      stock: 30,
      tags: ["heat tools", "brush"],
    },
    {
      name: "Sectioning Clips (Pack)",
      description: "Strong sectioning clips for styling control.",
      price: 3200,
      category: accessoriesCategory._id,
      stock: 110,
      tags: ["clips", "styling"],
    },
    {
      name: "Rat Tail Comb",
      description: "Precision parting comb for clean sections.",
      price: 2000,
      category: accessoriesCategory._id,
      stock: 140,
      tags: ["comb", "parting"],
    },
    {
      name: "Elastic Wig Band",
      description: "Adjustable elastic band for secure installs.",
      price: 2500,
      category: accessoriesCategory._id,
      stock: 130,
      tags: ["wig band"],
    },
    {
      name: "Wig Dryer Stand",
      description: "Hands-free drying stand for washed wigs.",
      price: 14000,
      category: accessoriesCategory._id,
      stock: 25,
      tags: ["drying", "wig care"],
    },
    {
      name: "Silk Bonnet",
      description: "Protects wigs and hairstyles overnight.",
      price: 4500,
      category: accessoriesCategory._id,
      stock: 95,
      tags: ["bonnet", "protection"],
    },
    {
      name: "Hair Oil Serum",
      description: "Lightweight serum for shine and frizz control.",
      price: 6000,
      category: accessoriesCategory._id,
      stock: 85,
      tags: ["serum", "shine"],
    },
    {
      name: "Lace Melting Band",
      description: "Elastic melt band for flawless lace installs.",
      price: 3500,
      category: accessoriesCategory._id,
      stock: 100,
      tags: ["lace", "install"],
    },
    {
      name: "Hair Steamer",
      description: "Moisture-infusing hair steamer for deep conditioning.",
      price: 35000,
      category: accessoriesCategory._id,
      stock: 15,
      tags: ["steamer", "treatment"],
    },
    {
      name: "Wig Styling Kit (Complete)",
      description: "All-in-one wig styling kit for professionals.",
      price: 55000,
      category: accessoriesCategory._id,
      stock: 10,
      tags: ["kit", "professional"],
    },
  ];

  await Product.insertMany(accessories);
  console.log("✅ Accessories seeded successfully");
}

module.exports = seedAccessories;
